use std::{error::Error as StdError, fs::File};

use futures_lite::future::{block_on, zip};
use garmin_importer::RouteImportReceipt;
use garmin_model::{
    artifact::AcquisitionOperationId,
    identity::{Source, SourceId},
    route::{RevisionProvenance, RevisionSource, RoutePlanRevision, RouteSport},
};
use garmin_storage::{CoursePersistenceError, Storage, snapshot::Limits};
use tempfile::{TempDir, tempdir};

use super::*;
use crate::RouteImportRequest;

type TestResult<T = ()> = Result<T, Box<dyn StdError>>;
const GPX: &[u8] = include_bytes!("../../../garmin-gpx/tests/fixtures/candidates.gpx");

struct Fixture {
    root: TempDir,
    application: Application,
    owner: UserContext,
    other: UserContext,
    receipt: RouteImportReceipt,
}

async fn fixture(geometry: bool) -> TestResult<Fixture> {
    let root = tempdir()?;
    let application = Application::new(Storage::open(root.path().join("courses.sqlite3")).await?);
    let owner = UserContext::new(application.create_profile("Walker".parse()?).await?.id());
    let other = UserContext::new(application.create_profile("Other".parse()?).await?.id());
    let source = Source::from_parts(
        SourceId::new_v4(),
        owner.user_id(),
        "GPX files".parse()?,
        None,
    );
    let document = Application::inspect_gpx(GPX)?;
    let candidate = document
        .candidates()
        .iter()
        .find(|candidate| candidate.shape().is_geometry() == geometry)
        .ok_or("missing GPX candidate")?;
    let receipt = application
        .import_route(RouteImportRequest::from_parts(
            owner,
            &source,
            "walk.gpx".parse()?,
            AcquisitionOperationId::new_v4(),
            time(),
            GPX,
            candidate.source(),
            "Morning walk".parse()?,
            RouteSport::Walking,
        ))
        .await?;
    Ok(Fixture {
        root,
        application,
        owner,
        other,
        receipt,
    })
}

fn time() -> Timestamp {
    Timestamp::from_unix_seconds(1_788_198_400).expect("valid fixture timestamp")
}

async fn generate(
    fixture: &Fixture,
    operation: CourseGenerationOperationId,
) -> TestResult<GeneratedCourse> {
    Ok(fixture
        .application
        .generate_course(
            fixture.owner,
            operation,
            fixture.receipt.revision_id(),
            time(),
        )
        .await?)
}

async fn bytes(
    application: &Application,
    owner: UserContext,
    record: &GeneratedCourse,
) -> TestResult<Vec<u8>> {
    application
        .course_artifact(owner, record.artifact_id())
        .await?
        .ok_or_else(|| "generated bytes missing".into())
}

async fn revise(fixture: &Fixture) -> TestResult<RoutePlanRevision> {
    let stored = fixture
        .application
        .route_plan(fixture.owner, fixture.receipt.plan_id())
        .await?
        .ok_or("missing route")?;
    let previous = stored.revision();
    let revision = RoutePlanRevision::from_parts(
        RoutePlanRevisionId::new_v4(),
        previous.plan_id(),
        Some(previous.id()),
        time(),
        "Changed hike".parse()?,
        RouteSport::Hiking,
        previous.shape().clone(),
        previous.cues().to_vec(),
        RevisionProvenance::from_parts(RevisionSource::Revision(previous.id()), Vec::new()),
    )?;
    fixture
        .application
        .storage
        .save_route_revision(fixture.owner.user_id(), stored.plan(), &revision)
        .await?;
    Ok(revision)
}

#[test]
fn generations_remain_bound_to_historical_revisions() -> TestResult {
    block_on(async {
        let fixture = fixture(true).await?;
        let first = generate(&fixture, CourseGenerationOperationId::new_v4()).await?;
        let original = bytes(&fixture.application, fixture.owner, &first).await?;
        let changed = revise(&fixture).await?;
        let second = generate(&fixture, CourseGenerationOperationId::new_v4()).await?;
        let current = fixture
            .application
            .generate_course(
                fixture.owner,
                CourseGenerationOperationId::new_v4(),
                changed.id(),
                time(),
            )
            .await?;
        assert_eq!(first.version().get(), 1);
        assert_eq!(second.version().get(), 1);
        assert_eq!(current.version().get(), 1);
        assert_eq!(first, second);
        assert_ne!(first.artifact_id(), current.artifact_id());
        assert_ne!(first.serial(), current.serial());
        assert_eq!(first.encoder().name(), garmin_fit::course::ENCODER_NAME);
        assert_eq!(first.generated_at(), time());
        assert_eq!(first.byte_count().as_u64(), original.len() as u64);
        let decoded = garmin_fit::course::decode(&original)?;
        assert_eq!(decoded.sport(), RouteSport::Walking);
        assert_eq!(decoded.name().as_str(), "Morning walk");
        let old = fixture
            .application
            .route_revision(fixture.owner, first.revision_id())
            .await?
            .ok_or("historical revision missing")?;
        assert_eq!(decoded.points().len(), old.shape().points().len());
        for (actual, expected) in decoded.points().iter().zip(old.shape().points()) {
            assert!(
                (actual.coordinate().latitude().as_degrees()
                    - expected.coordinate().latitude().as_degrees())
                .abs()
                    < 1e-6
            );
            assert!(
                (actual.coordinate().longitude().as_degrees()
                    - expected.coordinate().longitude().as_degrees())
                .abs()
                    < 1e-6
            );
        }
        let newest = bytes(&fixture.application, fixture.owner, &current).await?;
        assert_eq!(
            garmin_fit::course::decode(&newest)?.sport(),
            RouteSport::Hiking
        );
        assert_eq!(
            bytes(&fixture.application, fixture.owner, &first).await?,
            original
        );
        assert_eq!(
            fixture
                .application
                .generated_courses(fixture.owner, first.revision_id())
                .await?,
            vec![first]
        );
        assert_eq!(
            fixture
                .application
                .route_plan(fixture.owner, fixture.receipt.plan_id())
                .await?
                .ok_or("head missing")?
                .revision()
                .id(),
            changed.id()
        );
        fixture.application.close().await;
        Ok(())
    })
}

#[test]
fn retry_after_restart_returns_the_original_receipt_and_bytes() -> TestResult {
    block_on(async {
        let fixture = fixture(true).await?;
        let operation = CourseGenerationOperationId::new_v4();
        let first = generate(&fixture, operation).await?;
        let original = bytes(&fixture.application, fixture.owner, &first).await?;
        let changed = revise(&fixture).await?;
        fixture.application.close().await;
        let application =
            Application::new(Storage::open(fixture.root.path().join("courses.sqlite3")).await?);
        let retry = application
            .generate_course(
                fixture.owner,
                operation,
                first.revision_id(),
                Timestamp::from_unix_seconds(1_788_200_000)?,
            )
            .await?;
        assert_eq!(retry, first);
        assert_eq!(bytes(&application, fixture.owner, &retry).await?, original);
        assert_eq!(
            application
                .generated_courses(fixture.owner, first.revision_id())
                .await?
                .len(),
            1
        );
        assert!(matches!(
            application
                .generate_course(fixture.owner, operation, changed.id(), time())
                .await,
            Err(Error::Storage(garmin_storage::Error::Course(
                CoursePersistenceError::OperationConflict
            )))
        ));
        application.close().await;
        Ok(())
    })
}

#[test]
fn foreign_profiles_cannot_generate_list_or_download_courses() -> TestResult {
    block_on(async {
        let fixture = fixture(true).await?;
        let operation = CourseGenerationOperationId::new_v4();
        let first = generate(&fixture, operation).await?;
        for id in [operation, CourseGenerationOperationId::new_v4()] {
            assert!(matches!(
                fixture
                    .application
                    .generate_course(fixture.other, id, first.revision_id(), time())
                    .await,
                Err(Error::Storage(garmin_storage::Error::Course(
                    CoursePersistenceError::RevisionNotFound
                )))
            ));
        }
        assert!(
            fixture
                .application
                .generated_courses(fixture.other, first.revision_id())
                .await?
                .is_empty()
        );
        assert!(
            fixture
                .application
                .course_artifact(fixture.other, first.artifact_id())
                .await?
                .is_none()
        );
        assert!(
            fixture
                .application
                .course_artifact(fixture.owner, fixture.receipt.artifact_id())
                .await?
                .is_none()
        );
        fixture.application.close().await;
        Ok(())
    })
}

#[test]
fn concurrent_generations_reuse_the_artifact_and_coalesce_retries() -> TestResult {
    block_on(async {
        let fixture = fixture(true).await?;
        let (first, second) = zip(
            generate(&fixture, CourseGenerationOperationId::new_v4()),
            generate(&fixture, CourseGenerationOperationId::new_v4()),
        )
        .await;
        let (first, second) = (first?, second?);
        assert_eq!(first, second);
        let operation = CourseGenerationOperationId::new_v4();
        let (left, right) = zip(generate(&fixture, operation), generate(&fixture, operation)).await;
        let left = left?;
        assert_eq!(left, right?);
        assert_eq!(left, first);
        assert_eq!(left.version().get(), 1);
        assert_eq!(
            fixture
                .application
                .generated_courses(fixture.owner, first.revision_id())
                .await?
                .len(),
            1
        );
        fixture.application.close().await;
        Ok(())
    })
}

#[test]
fn encoding_failure_leaves_the_route_and_allocations_retryable() -> TestResult {
    block_on(async {
        let fixture = fixture(false).await?;
        let operation = CourseGenerationOperationId::new_v4();
        assert!(matches!(
            fixture
                .application
                .generate_course(
                    fixture.owner,
                    operation,
                    fixture.receipt.revision_id(),
                    time(),
                )
                .await,
            Err(Error::CourseEncoding(
                garmin_fit::course::Error::UnresolvedGeometry
            ))
        ));
        assert!(
            fixture
                .application
                .generated_courses(fixture.owner, fixture.receipt.revision_id())
                .await?
                .is_empty()
        );
        let resolved = fixture
            .application
            .confirm_route_straight_lines(fixture.owner, fixture.receipt.plan_id(), time())
            .await?;
        let generated = fixture
            .application
            .generate_course(fixture.owner, operation, resolved.revision().id(), time())
            .await?;
        assert_eq!(generated.version().get(), 1);
        assert_eq!(generated.serial().as_u32(), 1);
        assert_eq!(
            fixture
                .application
                .storage
                .artifact_bytes(fixture.receipt.artifact_id())
                .await?,
            Some(GPX.to_vec())
        );
        fixture.application.close().await;
        Ok(())
    })
}

#[test]
fn snapshot_restores_original_gpx_revisions_receipts_and_course_bytes() -> TestResult {
    block_on(async {
        let mut fixture = fixture(true).await?;
        let operation = CourseGenerationOperationId::new_v4();
        let first = generate(&fixture, operation).await?;
        let original = bytes(&fixture.application, fixture.owner, &first).await?;
        let changed = revise(&fixture).await?;
        let archive = fixture.root.path().join("snapshot.tar.zst");
        fixture
            .application
            .snapshot(fixture.owner, &archive, Limits::default())
            .await?;
        let prepared = fixture
            .application
            .prepare_restore(
                fixture.owner,
                File::open(archive)?,
                fixture.root.path(),
                Limits::default(),
            )
            .await?;
        let path = fixture.root.path().join("restored.sqlite3");
        prepared.publish(&path)?;
        fixture.application.close().await;
        let restored = Application::new(Storage::open(path).await?);
        assert_eq!(
            restored
                .generate_course(fixture.owner, operation, first.revision_id(), time())
                .await?,
            first
        );
        assert_eq!(bytes(&restored, fixture.owner, &first).await?, original);
        assert_eq!(
            restored
                .storage
                .artifact_bytes(fixture.receipt.artifact_id())
                .await?,
            Some(GPX.to_vec())
        );
        assert_eq!(
            restored.route_revision(fixture.owner, changed.id()).await?,
            Some(changed)
        );
        let next = restored
            .generate_course(
                fixture.owner,
                CourseGenerationOperationId::new_v4(),
                first.revision_id(),
                time(),
            )
            .await?;
        assert_eq!(next, first);
        restored.close().await;
        Ok(())
    })
}
