icon_catalog! {
    phosphor {
        ACTIVITY => phosphor_svgs::style::regular::PULSE,
        ARROWS_CLOCKWISE => phosphor_svgs::style::regular::ARROWS_CLOCKWISE,
        BICYCLE => phosphor_svgs::style::regular::BICYCLE,
        CALENDAR => phosphor_svgs::style::regular::CALENDAR,
        CAMERA => phosphor_svgs::style::regular::CAMERA,
        CARET_DOWN => phosphor_svgs::style::regular::CARET_DOWN,
        CARET_LEFT => phosphor_svgs::style::regular::CARET_LEFT,
        CARET_RIGHT => phosphor_svgs::style::regular::CARET_RIGHT,
        CHART_LINE => phosphor_svgs::style::regular::CHART_LINE,
        CHECK => phosphor_svgs::style::regular::CHECK,
        DATABASE => phosphor_svgs::style::regular::DATABASE,
        DESKTOP => phosphor_svgs::style::regular::DESKTOP,
        DOWNLOAD_SIMPLE => phosphor_svgs::style::regular::DOWNLOAD_SIMPLE,
        FILE => phosphor_svgs::style::regular::FILE,
        FOLDER_OPEN => phosphor_svgs::style::regular::FOLDER_OPEN,
        GEAR => phosphor_svgs::style::regular::GEAR,
        GLOBE => phosphor_svgs::style::regular::GLOBE,
        HARD_DRIVE => phosphor_svgs::style::regular::HARD_DRIVE,
        HOUSE => phosphor_svgs::style::regular::HOUSE,
        INFO => phosphor_svgs::style::regular::INFO,
        LIST => phosphor_svgs::style::regular::LIST,
        MAGNIFYING_GLASS => phosphor_svgs::style::regular::MAGNIFYING_GLASS,
        MAP_PIN => phosphor_svgs::style::regular::MAP_PIN,
        MAP_TRIFOLD => phosphor_svgs::style::regular::MAP_TRIFOLD,
        MINUS => phosphor_svgs::style::bold::MINUS,
        MOON => phosphor_svgs::style::regular::MOON,
        PATH => phosphor_svgs::style::regular::PATH,
        PENCIL => phosphor_svgs::style::regular::PENCIL,
        PERSON_SIMPLE_RUN => phosphor_svgs::style::regular::PERSON_SIMPLE_RUN,
        PLUS => phosphor_svgs::style::bold::PLUS,
        POWER => phosphor_svgs::style::regular::POWER,
        ROUTE => phosphor_svgs::style::regular::MAP_PIN_LINE,
        SIGN_OUT => phosphor_svgs::style::regular::SIGN_OUT,
        SUN => phosphor_svgs::style::regular::SUN,
        TRASH => phosphor_svgs::style::regular::TRASH,
        TRANSLATE => phosphor_svgs::style::regular::TRANSLATE,
        UPLOAD_SIMPLE => phosphor_svgs::style::regular::UPLOAD_SIMPLE,
        USER_CIRCLE => phosphor_svgs::style::regular::USER_CIRCLE,
        USERS => phosphor_svgs::style::regular::USERS,
        WARNING => phosphor_svgs::style::regular::WARNING,
        WATCH => phosphor_svgs::style::regular::WATCH,
        WIFI_SLASH => phosphor_svgs::style::regular::WIFI_SLASH,
        X => phosphor_svgs::style::regular::X,
    }
    local {
        WINDOW_MAXIMIZE => include_str!("../../assets/icons/window-maximize.svg"),
        WINDOW_RESTORE => include_str!("../../assets/icons/window-restore.svg"),
    }
}
