-- Retain retry identity and version allocation after deleting generated bytes.
CREATE TABLE course_generation_deletions (
    id TEXT PRIMARY KEY NOT NULL,
    operation_id TEXT NOT NULL UNIQUE,
    owner_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    revision_id TEXT NOT NULL
    REFERENCES route_plan_revisions (id) ON DELETE CASCADE,
    version INTEGER NOT NULL CHECK (version BETWEEN 1 AND 4294967295),
    UNIQUE (revision_id, version)
) STRICT;

CREATE INDEX artifacts_digest_idx ON artifacts (digest);
