[package]
name = "garmin-cli"
description = "Garmin Toolkit command-line application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
byte-unit.workspace = true
clap = { workspace = true, features = ["env"] }
crossterm.workspace = true
dirs.workspace = true
garmin-map-service.workspace = true
garmin-model.workspace = true
garmin-capture.workspace = true
garmin-device.workspace = true
garmin-i18n.workspace = true
garmin-progress.workspace = true
garmin-simulator.workspace = true
garmin-services.workspace = true
garmin-cli-tui.workspace = true
garmin-update.workspace = true
indoc.workspace = true
miette = { workspace = true, features = ["fancy"] }
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
sys-locale.workspace = true
tempfile.workspace = true
termcolor.workspace = true
termcolor-json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
